---
- name: "Check for user home - {{ item.name }}"
  ansible.builtin.stat:
    path: '{{ autologin_home_path }}/{{ item.name }}'
  changed_when: false
  register: home

- name: "Create home directory - {{ item.name }}"
  ansible.builtin.file:
    path: "{{ autologin_home_path }}/{{ item.name }}"
    state: directory
    mode: '0750'
    owner: "{{ item.name }}"
    group: "{{ autologin_group }}"
  when: not home.stat.exists

- name: Copy skeleton into home
  ansible.builtin.copy:
    src: /etc/skel/
    dest: "{{ autologin_home_path }}/{{ item.name }}"
    owner: "{{ item.name }}"
    group: "{{ autologin_group }}"
    mode: '0644'
  when: not home.stat.exists

- name: "Set authorized key on server - {{ item.name }}"
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.key }}"
