---
- name: "Check for user home"
  ansible.builtin.stat:
    path: '{{ autologin_home_path }}/{{ item.name }}'
  changed_when: false
  register: home

- name: "Create home directory"
  ansible.builtin.file:
    path: "{{ autologin_home_path }}/{{ item.name }}"
    state: directory
    mode: 0755
    owner: "{{ item.name }}"
    group: "{{ autologin_group }}"
  when: not home.stat.exists

- name: "Set authorized key on server"
  ansible.builtin.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.key }}"
